### ISSUE TITLE
Game crashing when accessing invalid Player submenu

### ISSUE THREAD

**Issue by gamerover98** [HowYouDoinMate/GrandTheftAutoV-Cheat#7]
When you are online and you are in the menu of a player, if he left the game and then you have to try to open the cheat menu, the game crashes.

**Comment by HowYouDoinMate** [comment]
Appreciate the report. I will look into this when the new DLC is going to be released, so that would be around the 15th as this is a sideproject and I don't have all time of the world available. Of course (if you have the required experience with C++) you can have a look yourself, in that case you can submit the potential solution through a Pull Request.

**Comment by HowYouDoinMate** [comment]
This issue has been resolved with the release of v1.3.0.2
